exports.USERS_ENDPOINT = process.env.USERS_ENDPOINT ||  "https://words-explorer-api.herokuapp.com/api/users"
exports.LOGIN_ENDPOINT = process.env.LOGIN_ENDPOINT || "https://words-explorer-api.herokuapp.com/api/auth/login"
exports.LOGOUT_ENDPOINT = process.env.LOGOUT_ENDPOINT || "https://words-explorer-api.herokuapp.com/api/auth/logout"
exports.REFRESH_ENDPOINT = process.env.REFRESH_ENDPOINT || "https://words-explorer-api.herokuapp.com/api/auth/refresh"
exports.GAMES_ENDPOINT = process.env.GAMES_ENDPOINT || "https://words-explorer-api.herokuapp.com/api/games"
exports.WORDS_ENDPOINT = process.env.WORDS_ENDPOINT || "https://words-explorer-api.herokuapp.com/api/words"