exports.REACT_APP_USERS_ENDPOINT = process.env.USERS_ENDPOINT ||  "//localhost:8080/api/users"
exports.REACT_APP_LOGIN_ENDPOINT = process.env.LOGIN_ENDPOINT || "//localhost:8080/api/auth/login"
exports.REACT_APP_LOGOUT_ENDPOINT = process.env.LOGOUT_ENDPOINT || "//localhost:8080/api/auth/logout"
exports.REACT_APP_REFRESH_ENDPOINT = process.env.REFRESH_ENDPOINT || "//localhost:8080/api/auth/refresh"
exports.REACT_APP_GAMES_ENDPOINT = process.env.GAMES_ENDPOINT || "//localhost:8080/api/games"
exports.REACT_APP_WORDS_ENDPOINT = process.env.WORDS_ENDPOINT || "//localhost:8080/api/words"